from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship
from app.database import Base


class User(Base):
    """
    Users table - stores platform administrative and security user accounts.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    role = Column(String, nullable=False, default="analyst")

    # Relationships
    assigned_alerts = relationship("Alert", back_populates="assignee")


class Employee(Base):
    """
    Employees table - stores records of monitored employees within the organization.
    """
    __tablename__ = "employees"

    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(String, unique=True, index=True, nullable=False)
    name = Column(String, nullable=False)
    department = Column(String, nullable=False)
    designation = Column(String, nullable=False)
    manager_id = Column(Integer, ForeignKey("employees.id"), nullable=True)
    device_info = Column(Text, nullable=True)
    access_privileges = Column(Text, nullable=True)

    # Relationships
    manager = relationship("Employee", remote_side=[id], backref="subordinates")
    incidents = relationship("Incident", back_populates="employee")
    alerts = relationship("Alert", back_populates="employee")


class Incident(Base):
    """
    Incidents table - tracks security incidents created during investigations.
    """
    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(Integer, ForeignKey("employees.id"), nullable=False)
    status = Column(String, nullable=False, default="open")
    severity = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    employee = relationship("Employee", back_populates="incidents")


class Alert(Base):
    """
    Alerts table - stores security alerts generated by the system.
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    employee_id = Column(Integer, ForeignKey("employees.id"), nullable=False)
    severity = Column(String, nullable=False)
    message = Column(String, nullable=False)
    status = Column(String, nullable=False, default="UNASSIGNED")
    details = Column(Text, nullable=True)
    recommended_action = Column(Text, nullable=True)
    assigned_to = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    employee = relationship("Employee", back_populates="alerts")
    assignee = relationship("User", back_populates="assigned_alerts")

